name: ci

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          wget "https://github.com/Jarred-Sumner/bun-install-bug-repro-9430/releases/download/asdasfasd/bun"
          chmod +x bun
          ./bun install --verbose
